### ISSUE TITLE
Notice customization

### ISSUE THREAD

**Issue by AlexDenisov** [tciuro/NoticeView#11]
Hi, could you add some interface to simple NoticeView customization (at least the colors)?
I can edit source code at Red/Green/Blue notices, but if I add NV as submodule or pod (CocoaPods), then this  changes can't be stored in the repo...

**Comment by tciuro** [comment]
Alex, it's not that simple. It's not one RGB color. There are a bunch of them: 8 in WBErrorNoticeView, 8 in WBSuccessNoticeView and 6 in WBStickyNoticeView.

These are the colors as shown by Tweetbot. You're free to subclass WBBaseNoticeView or any of its subclasses and implement the gradient in any way you wish. I prefer to keep the project true to Tweetbot.
