### ISSUE TITLE
Two faults in WBBaseNoticeView.m

### ISSUE THREAD

**Issue by honood** [tciuro/NoticeView#16]
1st: line 17
if (self == [super init]) {     ----->     if (self = [super init]) {

2nd: line 41
The datatype of _cmd is SEL, maybe use NSStringFromSelector(_cmd) instead, and change the format specifier from %s to %@.

**Comment by tciuro** [comment]
Nice catch, thanks. These two bugs have been fixed together with an iOS 6 issue I found. I cannot submit it yet due to the NDA. I will submit the fixes as soon as iOS is released.
