### ISSUE TITLE
View does not size to larger than iPhone width on iPad

### ISSUE THREAD

**Issue by robotpukeko** [tciuro/NoticeView#3]
Hi,

I've implemented NoticeView using the instructions provided, but have found that the notice view doesn't resize it's width on the iPad when I try and add it to the detail view controller of a split view controller.

It appears at the same width as the 320pt specified in WBNoticeView.m - _showNoticeOfType method, when the noticeView is initialised with a CGRect.  It seems as though the view isn't adhering to the setting of the AutoresizeMask for width and height.

See the screenshot below.

http://d.pr/i/qs0n

If I replace the fixed width specified in the initWithFrame with the width of the view passed, it works :

```
CGFloat currentViewWidth = view.frame.size.width;
self.noticeView = [[UIView alloc]initWithFrame:CGRectMake(0.0, -60.0, currentViewWidth, noticeViewHeight)];
```

Can you let me know if the alert should be autoresizing to the width of the view?

Thanks,
Steve

**Comment by tciuro** [comment]
It should work, but wasn't implemented yet. I have committed the changes, including the automatic resize of NoticeView based on text length (previously it was limited to 2 lines of text.)

Thanks for reporting it.

https://github.com/tciuro/NoticeView/commit/35a7275ee4d03e7f15ec9b92c91fc7740814d4a9

**Comment by robotpukeko** [comment]
One question... will using the width of UIScreen rather than UIView mean that if I applied the NoticeView to the detail view controller (the right side of the split view controller), the message would still fit to that view? From my understanding, using the width from the bounds of UIScreen would give you the width of the whole device screen instead?

**Comment by tciuro** [comment]
Sorry I closed the issue too soon. That is an excellent point. You're right, the NoticeView as it currently stands would be displayed across the entire screen.

I believe I could get the dimensions of the view passed by the client and limit the NoticeView to those dimensions. I'll try that later and report back. Thanks again.

**Comment by tciuro** [comment]
I have fixed the bug. Now, the notice view adopts the width of the view that it's related to:

https://github.com/tciuro/NoticeView/commit/1510116ba3b432bf41214d73bb604716604ecc6e

I have also added an iPad demo to show how this works.
